name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.9.7'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="./vars/robopd2.tfvars" -out=tfplan

      - name: Manual Approval
        id: approval
        uses: peter-evans/approval-action@v2
        with:
          message: 'Please review and approve the Terraform changes'

      - name: Terraform Apply
        if: steps.approval.outputs.approved == 'true'
        run: terraform apply tfplan
