name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform  # Update this path

    env:
      TF_VAR_FILE: "./vars/robopd2.tfvars"
      PLAN_OUT_FILE: "tfplan.out"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.7'  # Specify your desired Terraform version

      - name: Terraform Format
        run: terraform fmt -recursive -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file="${{ env.TF_VAR_FILE }}" -out="${{ env.PLAN_OUT_FILE }}"

      - name: Upload plan file
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ${{ env.PLAN_OUT_FILE }}

      - name: Download plan file
        if: github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply "${{ env.PLAN_OUT_FILE }}"
